#encoding: utf-8 
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

Question.delete_all
q1 = Question.create! :text=>"Wolves can double their numbers every year. They do not do so, however, if the area in which they live is already full and the territory of each pack borders on the territory of other packs on all sides. Lone wolves, unable to establish a territory near their place of origin, disperse to a less desirable habitat and often are hunted by people. Which of the following conclusions may be properly drawn from the information in the passage above?", :answers => ["The number of wolves in any area suitable for wolves may be predicted to quadruple in two years.", "Wolves are ejected from the pack to wander singly as lone wolves when the number of wolves in the pack has doubled.", "The amount of territory suitable for wolves has been diminishing in recent years as a result of human encroachment, with a resulting diminution in the wolf population.", "Wolf hunting can continue at a moderate rate on the fringes of a good habitat for wolves without a decrease in the average yearly wolf population in that territory.", "The wolf population density in a given area of wolf territory does not vary with the yearly rate of wolf reproduction."], :correct_answer_index => 3
Question.create(text:"The TJ-700 and the Beta Turbomax are two models of cars of different manufacturers.  These two models have almost identical specifications and features, and they sell for almost the same price. Both were introduced on the market five years ago, and each year, the respective manufacturers spend about the same amount in advertising. In the past five years, the total number of TJ-700's sold is about 80% greater than the total number of Beta Turbomax's sold. Clearly, the advertising firm that created TJ-700 ads created much more effective ads than the firm that created Beta Turbomax ads. In evaluating the argument, it would be most useful to know which of the following?",answers: ["How the advertising budgets over the last five years for the TJ-700 and the Beta Turbomax compare to the budgets over the same period for comparable models of other manufacturers.", "Whether the ads for the TJ-700 and the Beta Turbomax included the address or websites of local dealerships selling these models.", "Whether buyers of the TJ-700 and the Beta Turbomax reported being familiar with the ads of these cars.", "What percentage the first two years maintenance costs of each model is of their respective advertising budgets.", "Whether buyer of cars of other manufacturers in the last five years are familiar with the ads for the TJ-700 and the Beta Turbomax."],correct_answer_index: 2)
Question.create(text:"The Food and Drug Administration Agency’s latest research has just been released. Studies conducted on laboratory rats demonstrate that when pregnant rats are given doses of caffeine equivalent to a human consumption of six cups of coffee per day, the rate of birth defects increases. A spokesperson for the FDA, when asked if the government would require warning labels on products containing caffeine, replied that it would not, because if the findings of these studies are refuted, the government will lose credibility. The government’s position on requiring warning labels on caffeinated products most strongly suggests which of the following?",answers: ["concern about imposing a warning that applies only to part of the population", "a reluctance to impose a warning when limited consumption may be harmless", "doubts about the conclusive nature of the studies", "a reluctance to draw conclusions about human birth defects from studies on animals", "doubts about the seriousness of the birth defects"],correct_answer_index: 2)
Question.create(text:"Studies have revealed that most American homeowners consider the ideal home to be one that is one-third larger and two-thirds more expensive than the homes they own. Which of the following can be inferred from this finding?",answers: ["Most homeowners would probably be willing to work a second job to afford the home of their dreams.", "Most homeowners consider their home their most important material item.", "Most homeowners are not entirely satisfied with the homes they own.", "The best homes are the largest and most expensive ones.", "Most people would be satisfied with their home if their home’s property value suddenly increased."],correct_answer_index: 2)
Question.create(text:"Tests demonstrating that the olfactory bulbs (relating to the sense of smell) of salmon will react upon exposure only to water from their spawning ground and no other water suggest the possibility that repeated exposure to a specific odorant of their spawning area during the first few weeks of life could stimulate olfactory receptor sites, increasing olfactory sensitivity to that single scent and influencing salmon migration to their spawning area. Which of the following statements, if true, would seriously weaken the author’s conclusion?",answers: ["Salmon have been trained, through repeated exposure, to recognize phenol and distinguish it from closely related pchlorphenol, in concentrations as small as five parts per billion.", "A dog can detect and distinguish the odor of a single human fingerprint for as long as six weeks, after which time the scent usually fades away.", "Salmon have been successfully stocked in rivers where special salmon \"runs\" have been constructed.", "Women are acutely aware of the odor of a synthetic steroid named exaltolide, which most men are unable to detect.", "Salmon spawned and raised in hatcheries will return to the spawning ground of their parents, and not to the source of the water (the hatcheries) in which they were spawned."],correct_answer_index: 4)
Question.create(text:"Every month, Amy tallies the number of cakes her bakery produced but failed to sell. In June, this figure was higher than it was in May. If the statements above are true, which of the following must also be true?",answers: ["Amy’s bakery sold more cakes in May than it sold in June.", "Amy’s bakery baked more cakes in May than it baked in June.", "Amy’s bakery sold more cakes in June than it sold in May.", "Amy’s bakery produced more cakes in June than it sold in June.", "Amy’s bakery sold more cakes in May than it baked in June."],correct_answer_index: 3)
Question.create(text:"Epidemiologist: Malaria passes into the human population when a mosquito carrying the virus bites a human who has no immunity. The malaria parasite can remain for up to forty days in the blood of an infected person. The disease cannot be passed from person to person, unless a non-infected person is exposed to the blood of an infected person. Theoretically, malaria could be eradicated in any given area, if all the mosquitoes carrying malaria in that area are exterminated. If such a course of action is carried out at a worldwide level, then the global eradication of malaria is possible. Which of the following, if true, suggests that the epidemiologist’s plan for eliminating malaria is not viable?",answers: ["A person who is infected with malaria can infect a mosquito that is not carrying malaria, if that mosquito bites such a person.", "Unless a mosquito bites an infected person, and then bites a non-infected person, malaria cannot be passed directly from human to human.", "Malaria is still endemic in many parts of the world, and many health workers believe that the global eradication of malaria is not possible.", "Some people in areas where malaria is rife have developed an immunity to mosquitos, yet they are also show a higher incidence of genetic disorders such as sickle-cell anemia.", "Mosquitos in many developing parts of the world are responsible for passing on a variety of viruses to human hosts."],correct_answer_index: 0)
Question.create(text:"A sports arena is considering a new stadium design, one in which each block of seats would be in an enclosed weather-proof room with a view of the playing field and a large screen TV showing the action of play, including the instant replays typical of television broadcasts of sports games.  The developer reasons that exposure to elements and lack of access to instant replays significantly limits the typical spectator's enjoyment of the live game. This stadium design would be unlikely to increase the pleasure the spectators take from live games if they enjoyed:", answers: ["watching the game without interruptions from other spectators", "coming to multiple games in a single season", "viewing on a large screen television at home all games which they do not attend live", "feeling the immediate camaraderie with the crowd of other spectators at the game", "attending evening games more than midday games."],correct_answer_index: 3)
Question.create(text:"Studies undertaken by institutions for higher education reveal that most college students consider their grade point average not to be reflective of their actual academic abilities. The students indicate that they feel their GPA should be one-quarter to three-quarters of a point above their actual GPA, no matter what their actual GPA may be. Which of the following can be logically inferred from these studies?",answers: ["Most college students are more concerned with their GPA than with acquiring knowledge.", "Most college students do not have enough time to study, so their GPA suffers.", "Most college students are not satisfied with their GPAs.", "Most college students feel that a strong GPA is necessary to attract potential employers or to gain admission to graduate school.", "The better college students feel that their GPA is more reflective of their actual academic abilities than do poorer students."],correct_answer_index: 2)
Question.create(text:"Recording Agent: Music industry representatives often advance the claim that online file sharing, (which allows someone who purchased a music CD to share contents with others using their computers—at no additional cost), hurts their business. Since the advent of file sharing, however, music CD sales have actually risen; therefore, file sharing does not hurt the music business. In fact, file sharing seems to have had a positive effect on the music industry. The argument above is most vulnerable to criticism on the grounds that it",answers: ["is a circular argument, assuming what the argument sets out to prove", "defies common sense, since people will not pay for music they can acquire for free", "fails to specify how much music CD sales have risen since the advent of file sharing", "assumes a causal relationship between variables with a high correlation without examining other potential factors", "denies the legitimacy of a claim on the basis of the bias interest of those (music industry representatives) making the claim"],correct_answer_index: 3)
Question.create(text:"Soft Drinks Manufacturer: Despite attractive offers, our company has rejected any plans to expand our market into the Czech Republic at this time.  We simply have no data on how well received our products would be in the Czech Republic. Industry Analyst: Your position is inconsistent.  Last year, you expended into Bolivia, even after taste tests had definitely found that approximately 40% of the Bolivian population did not care for any of your products. Therefore, concerns about how well received your product will be cannot be motivating this position. The industry analyst's argument is flawed because it fails to consider that:",answers: ["the company's most popular soft drink in Bolivia might be different from the company's most popular soft drink in the Czech Republic.", "coffee is more popular than most soft drinks in both Bolivia and in the Czech Republic", "the Czech currency is much stronger than the Boliviano, the national currency of Bolivia.", "the results of taste tests in a particularly country can change over the years as different beverages are sold in that country.", "known risks can be assessed, but unknown risks cannot."],correct_answer_index: 4)
Question.create(text:"The element ytterbium increases its electrical resistance when subject to high mechanical stresses.  This property has made it an indispensable component in a medical tool designed to measure the stress on bones, which can guide physicians in setting broken bones. Unfortunately, ytterbium is rare, found in only a few meager sources around the world.  A steep market demand will cause the price to skyrocket, and this technology so helpful to physicians will become unaffordable. Which of the following, if true, most seriously weakens the argument above?",answers: ["Just one mining company controls all the ytterbium that is imported into the United States, where these medical tools are manufactured.", "The process of extracting pure ytterbium from its ores, euxenite and xenotime, is very expensive and involves strong acids.", "Ytterbium is also used as an additive, in small quantities, to stainless steel and solid-state lasers.", "Some common alloys of tin also increase their electrical resistance under mechanical loads.", "The largest source of ytterbium is in a relatively remote region of China."],correct_answer_index: 3)
Question.create(text:"With the decline of predators, such as wolves and coyotes, that used to keep the deer population within certain limits, deer have increased in numbers until they cannot feed themselves in the forest alone but must forage on open rangeland in competition with cattle. Thus, in areas where forest borders on rangeland, deer hunting is an essential activity. This argument would be most seriously weakened if it could be shown that",answers: ["deer hunters are not concerned about the prosperity of ranchers", "wolves and coyotes do not prey upon deer only", "deer and cattle do not eat the same plants", "deer hunting is popular even in areas where the forest does not border rangeland", "the deer population may someday be hunted out of existence"],correct_answer_index: 2)
Question.create(text:"A research scientist attempted to prove that chocolate helps people quit smoking cigarettes. In formulating this clinical study the scientist divided 100 smokers into two groups of 50 each. Members of group A were given a piece of chocolate every time they wanted a cigarette. Group B members were given a piece of gum every time they wanted a cigarette. At the end of the experiment, there was no significant difference between the two groups in terms of success at quitting smoking. Accordingly, the scientist concluded that chocolate does not help people quit smoking. Which of the following is the most effective criticism of the results of the experiment?",answers: ["The scientist should have used a larger population of smokers from which to draw the sample.", "The scientist should have extended the clinical studies to better assess the long-term effects of the experiment.", "The scientist should have instead concluded that chocolate does not help people quit smoking any more than gum helps people quit smoking.", "The scientist should have given the subjects their choice of candy and gum to factor in personal preferences.", "The scientist should not have substituted one oral habit for another, which may have introduced a clinical bias."],correct_answer_index: 2)
Question.create(text:"Prof. Hernandez's monumental work The History of Central America covers everything about the region from the origin of the Mesoamerican period to the end of the Cold War.  While the book has several informative maps and charts, many of the chapters spend less time describing facts and more time explaining Prof. Hernandez's theories.  Indeed, the last two chapters consist exclusively of his exposition of theory of the role of Central America in post WWII world politics.  Therefore, properly speaking, this book is not a history book. Which of the following is an assumption that supports drawing the conclusion above from the reasons given for that conclusion?",answers: ["Some history books consist almost exclusively of catalogues of historical facts.", "Different historians have different understanding of the relative importance between facts and theories within the study of history.", "Historians should be more explicit than most are now about the theoretical framework with which they write.", "History as a discipline is concerned only with historical facts, not with the theoretical explanations of those facts.", "Most books that present a wealth of historical facts include maps and charts as well."],correct_answer_index: 3)
Question.create(text:"Sixty years ago, cancer was not as prevalent as it is today. In the 1980s, it became an epidemic. Of course, 60 years ago there were no preservatives, additives, or artificial ingredients used in food processing. Therefore, the many medical authorities who believe these items cause cancer are correct. The logic of the author’s statement would be weakened if it were pointed out that",answers: ["cancer study and research has become a specialty at many medical schools", "preservatives, additives, and artificial ingredients have been in existence for no more than 60 years", "six to seven decades ago, death from cancer was not recognized and often the reason for death by cancer was listed as natural causes.", "preservatives were not included in packaged foods until the 1960s", "diet and health have been linked by medical experts for decades"],correct_answer_index: 2)
Question.create(text:"Ornithologist: Eagles suffer about twice as many unhatched eggs because of shell damage as do non predatory birds. This high rate of egg failure also holds true for hawks and owls. Ornithologists have long hypothesized that this problem among birds of prey may be due to pesticide traces left in their food supply. Which of the following statements about birds of prey would most likely tend to confirm the ornithologists’ hypothesis?",answers: ["The egg failure rate for birds of prey in pesticide-free wilderness areas is the same as for non predatory birds in the same areas.", "High egg failure rate is common among all endangered birds.", "Because birds of prey eat carrion, it is difficult to predict the exact contents of their diet.", "The egg failure rate for non predatory birds is slightly higher in cultivated areas than in wilderness areas.", "No significant difference in pesticide sensitivity has been found between eagles and hawks."],correct_answer_index: 0)
Question.create(text:"Due to an easing of state sanctions against hunting, Deersdale Preserve has experienced an influx of hunters in the last several months. During this time, the silvertail fox, a popular target for hunters, has seen a marked decrease in population.  Therefore, to prevent the population of silvertail fox—an important apex predator responsible for keeping the Deersdale County’s rabbit population in check—from falling even lower, the state should once again place strict sanctions against hunting.Which of the following, if true, may suggest that stricter sanctions against hunting would not have the desired effect?",answers: ["The population of rabbits has surged ever since the hunting sanctions in Deersdale County were lifted.","The silvertail fox population varies greatly throughout the year, especially during winter when prey becomes scarce.", "The local authorities are expecting even more hunters in the coming year to arrive to the park.","The silvertail fox had been experiencing a population surge shortly before the state sanctions against hunting were eased.","The grey wolf, a large predator that competes with the silvertail fox over Deersdale Preserve’s rabbit population, has seen its numbers decrease since the arrival of the hunters."],correct_answer_index: 1)
Question.create(text: "The rate of health complications of patients on intravenous (IV) therapy at a particular hospital was higher than usual. Government inspectors found that the typical IV solutions used in this hospital had somewhat high concentrations of sodium and potassium, which were raising patients' blood pressure and taxing their kidneys. The government inspectors mandated lowering the sodium and potassium in these IV preparations, and threatened with a possible government fine.  In compliance, the hospital lowered the sodium and potassium levels in the IV solutions to the correct levels.  Nevertheless, patients on IV therapy at that hospital continued to have a high rate of health complications. Which of the following, if true, most helps to explain why acting on the government inspectors' recommendations failed to achieve its goal?",answers: ["The change in IV solution procedure meant a number of related legal documents had to be renegotiated and rewritten, at great cost.","When sodium and potassium levels in the blood fall below their baseline level, it can damage cells throughout the body by reverse osmosis.","It is typical for a patient's appetite to increase to healthy levels once they have completed a course of IV therapy.", "A high proportion of patients at this hospital are older, and older patients are more vulnerable to infections that can accompany IVs.", "Because the findings were published in the news, some patients have chosen to use another hospital in the region."],correct_answer_index: 3, explanation: "TO BE DETERMINED")
Question.create(text:"The number of sports cars per square mile is 40% greater in downtown Terrera than in downtown Goldsville. If the entire metropolitan area of each city is compared—which includes downtown as well as suburbs and exurbs—then the number of sports cars per square mile is 20% greater in Goldsville. Based on the information above, which of the following can be inferred?",answers: ["There is a greater number of sports cars in the suburbs and exurbs of Goldsville than in those of Terrera.", "In total, there is a greater number of sports cars in metropolitan Goldsville than in metropolitan Terrera.","Metropolitan Goldsville covers a larger area than metropolitan Terrera.", "Per square mile, there are fewer sports cars in the exurbs and suburbs of Terrera than in those of Goldsville.","The number of sports cars per square mile is greater in downtown Goldsville than in the suburbs and exurbs of Goldsville."],correct_answer_index: 3)

# Default template page

Template.delete_all
template1 = Template.create! :name => 'Default', :html => <<EndOfPage
<!DOCTYPE html>
<html>
  <head>
    <title>MOOCchat Default Template</title>
    <link rel="stylesheet" type="text/css" href="/public/stylesheets/default.css" media="all"/>
  </head>
  <body>
    <div id="main">
      <h1>Default Template</h1>
      <p>This is a MOOCchat default page template.</p>
    </div>
    <div id="footer">
      <p>Page ID: <%= @page_id %> </p>
    </div>
  </body>
</html>

EndOfPage

Condition.delete_all
Condition.create!(name: "Chat Sequence 1",prologue_pages: [template1],body_pages: [],epilogue_pages: [],preferred_group_size: 1, minimum_group_size:1)

Cohort.delete_all
cohort = Cohort.create!(name: "Cohort 1")

ActivitySchema.delete_all
ActivitySchema.create!(name: "Quiz Review", cohort: cohort, enabled: true, randomized: false, num_questions: 1, tag: "Quiz Review", questions: [q1], start_time: Time.zone.now, end_time: Time.zone.now + 2.days, starts_every: 5)

