# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)
Question.create(text:"Wolves can double their numbers every year. They do not do so, however, if the area in which they live is already full and the territory of each pack borders on the territory of other packs on all sides. Lone wolves, unable to establish a territory near their place of origin, disperse to a less desirable habitat and often are hunted by people. Which of the following conclusions may be properly drawn from the information in the passage above?",answers: ['The number of wolves in any area suitable for wolves may be predicted to quadruple in two years.', 'Wolves are ejected from the pack to wander singly as lone wolves when the number of wolves in the pack has doubled.', 'The amount of territory suitable for wolves has been diminishing in recent years as a result of human encroachment, with a resulting diminution in the wolf population.', 'Wolf hunting can continue at a moderate rate on the fringes of a good habitat for wolves without a decrease in the average yearly wolf population in that territory.', 'The wolf population density in a given area of wolf territory does not vary with the yearly rate of wolf reproduction.'],correct_answer_index: 3)
Question.create(text:"The TJ-700 and the Beta Turbomax are two models of cars of different manufacturers.  These two models have almost identical specifications and features, and they sell for almost the same price. Both were introduced on the market five years ago, and each year, the respective manufacturers spend about the same amount in advertising. In the past five years, the total number of TJ-700's sold is about 80% greater than the total number of Beta Turbomax's sold. Clearly, the advertising firm that created TJ-700 ads created much more effective ads than the firm that created Beta Turbomax ads. In evaluating the argument, it would be most useful to know which of the following?",answers: ["How the advertising budgets over the last five years for the TJ-700 and the Beta Turbomax compare to the budgets over the same period for comparable models of other manufacturers.", "Whether the ads for the TJ-700 and the Beta Turbomax included the address or websites of local dealerships selling these models.", "Whether buyers of the TJ-700 and the Beta Turbomax reported being familiar with the ads of these cars.", "What percentage the first two years maintenance costs of each model is of their respective advertising budgets.", "Whether buyer of cars of other manufacturers in the last five years are familiar with the ads for the TJ-700 and the Beta Turbomax."],correct_answer_index: 2)
Question.create(text:"The Food and Drug Administration Agency’s latest research has just been released. Studies conducted on laboratory rats demonstrate that when pregnant rats are given doses of caffeine equivalent to a human consumption of six cups of coffee per day, the rate of birth defects increases. A spokesperson for the FDA, when asked if the government would require warning labels on products containing caffeine, replied that it would not, because if the findings of these studies are refuted, the government will lose credibility. The government’s position on requiring warning labels on caffeinated products most strongly suggests which of the following?",answers: ["concern about imposing a warning that applies only to part of the population", "a reluctance to impose a warning when limited consumption may be harmless", "doubts about the conclusive nature of the studies", "a reluctance to draw conclusions about human birth defects from studies on animals", "doubts about the seriousness of the birth defects"],correct_answer_index: 2)
Question.create(text:"Studies have revealed that most American homeowners consider the ideal home to be one that is one-third larger and two-thirds more expensive than the homes they own. Which of the following can be inferred from this finding?",answers: ["Most homeowners would probably be willing to work a second job to afford the home of their dreams.", "Most homeowners consider their home their most important material item.", "Most homeowners are not entirely satisfied with the homes they own.", "The best homes are the largest and most expensive ones.", "Most people would be satisfied with their home if their home’s property value suddenly increased."],correct_answer_index: 2)
Question.create(text:"Tests demonstrating that the olfactory bulbs (relating to the sense of smell) of salmon will react upon exposure only to water from their spawning ground and no other water suggest the possibility that repeated exposure to a specific odorant of their spawning area during the first few weeks of life could stimulate olfactory receptor sites, increasing olfactory sensitivity to that single scent and influencing salmon migration to their spawning area. Which of the following statements, if true, would seriously weaken the author’s conclusion?",answers: ["Salmon have been trained, through repeated exposure, to recognize phenol and distinguish it from closely related pchlorphenol, in concentrations as small as five parts per billion.", "A dog can detect and distinguish the odor of a single human fingerprint for as long as six weeks, after which time the scent usually fades away.", "Salmon have been successfully stocked in rivers where special salmon \"runs\" have been constructed.", "Women are acutely aware of the odor of a synthetic steroid named exaltolide, which most men are unable to detect.", "Salmon spawned and raised in hatcheries will return to the spawning ground of their parents, and not to the source of the water (the hatcheries) in which they were spawned."],correct_answer_index: 4)
Question.create(text:"Every month, Amy tallies the number of cakes her bakery produced but failed to sell. In June, this figure was higher than it was in May.</p><p>&emsp;If the statements above are true, which of the following must also be true?",answers: ["Amy’s bakery sold more cakes in May than it sold in June.", "Amy’s bakery baked more cakes in May than it baked in June.", "Amy’s bakery sold more cakes in June than it sold in May.", "Amy’s bakery produced more cakes in June than it sold in June.", "Amy’s bakery sold more cakes in May than it baked in June."],correct_answer_index: 3)
Question.create(text:"Epidemiologist: Malaria passes into the human population when a mosquito carrying the virus bites a human who has no immunity. The malaria parasite can remain for up to forty days in the blood of an infected person. The disease cannot be passed from person to person, unless a non-infected person is exposed to the blood of an infected person. Theoretically, malaria could be eradicated in any given area, if all the mosquitoes carrying malaria in that area are exterminated. If such a course of action is carried out at a worldwide level, then the global eradication of malaria is possible.</p><p>&emsp;Which of the following, if true, suggests that the epidemiologist’s plan for eliminating malaria is not viable?",answers: ["A person who is infected with malaria can infect a mosquito that is not carrying malaria, if that mosquito bites such a person.", "Unless a mosquito bites an infected person, and then bites a non-infected person, malaria cannot be passed directly from human to human.", "Malaria is still endemic in many parts of the world, and many health workers believe that the global eradication of malaria is not possible.", "Some people in areas where malaria is rife have developed an immunity to mosquitos, yet they are also show a higher incidence of genetic disorders such as sickle-cell anemia.", "Mosquitos in many developing parts of the world are responsible for passing on a variety of viruses to human hosts."],correct_answer_index: 0)
Question.create(text:"A sports arena is considering a new stadium design, one in which each block of seats would be in an enclosed weather-proof room with a view of the playing field and a large screen TV showing the action of play, including the instant replays typical of television broadcasts of sports games.  The developer reasons that exposure to elements and lack of access to instant replays significantly limits the typical spectator's enjoyment of the live game.</p><p>&emsp;This stadium design would be unlikely to increase the pleasure the spectators take from live games if they enjoyed:</p>", answers: ["watching the game without interruptions from other spectators", "coming to multiple games in a single season", "viewing on a large screen television at home all games which they do not attend live", "feeling the immediate camaraderie with the crowd of other spectators at the game", "attending evening games more than midday games."],correct_answer_index: 3)
Question.create(text:"Studies undertaken by institutions for higher education reveal that most college students consider their grade point average not to be reflective of their actual academic abilities. The students indicate that they feel their GPA should be one-quarter to three-quarters of a point above their actual GPA, no matter what their actual GPA may be.</p><p>&emsp;Which of the following can be logically inferred from these studies?",answers: ["Most college students are more concerned with their GPA than with acquiring knowledge.", "Most college students do not have enough time to study, so their GPA suffers.", "Most college students are not satisfied with their GPAs.", "Most college students feel that a strong GPA is necessary to attract potential employers or to gain admission to graduate school.", "The better college students feel that their GPA is more reflective of their actual academic abilities than do poorer students."],correct_answer_index: 2)
Question.create(text:"Recording Agent: Music industry representatives often advance the claim that \"online file sharing,\" (which allows someone who purchased a music CD to share contents with others using their computers—at no additional cost), hurts their business. Since the advent of file sharing, however, music CD sales have actually risen; therefore, file sharing does not hurt the music business. In fact, file sharing seems to have had a positive effect on the music industry.</p><p>&emsp;The argument above is most vulnerable to criticism on the grounds that it",answers: [],correct_answer_index: 3)
Question.create(text:"",answers: [],correct_answer_index: 4)
Question.create(text:"",answers: [],correct_answer_index: 3)
Question.create(text:"",answers: [],correct_answer_index: 2)
Question.create(text:"",answers: [],correct_answer_index: 2)
Question.create(text:"",answers: [],correct_answer_index: 3)
Question.create(text:"",answers: [],correct_answer_index: 2)
Question.create(text:"",answers: [],correct_answer_index: 0)
Question.create(text:"",answers: [],correct_answer_index: 1)
Question.create(text:"",answers: [],correct_answer_index: 3)
Question.create(text:"",answers: [],correct_answer_index: 3)

